language: c++

env:
  - PYTHON_VERSION=3.4.3
  - PYTHON_VERSION=3.6.3
  - PYTHON_VERSION=3.7.1

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9.3

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then date -u; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then uname -a; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install mesa-common-dev libgl1-mesa-dev mesa-utils-extra libglapi-mesa ninja-build libqt4-dev qt4-qmake libqt4-opengl-dev; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 30 brew tap cartr/qt4; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 30 brew tap-pin cartr/qt4; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 30 brew install cartr/qt4/qt ninja; fi

script:
  - cd bin
  - cmake -GNinja -DTRAVIS_BUILD:BOOL=ON -DUSER_PYTHON_VERSION="${PYTHON_VERSION}" ../Superbuild
  - travis_wait 80 ninja
  - cd SCIRun
  - ./Algorithm_Layer_Test
  - ./Modules_Factory_Tests --gtest_filter=*HardCodedModuleFactoryTests*

notifications:
  slack: sciinstitute:lZnpQQXNd4Io5iGDPQDpJmI1
