language: c++

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
#    - os: osx
#      osx_image: xcode7.2

before_install:
- date -u
- uname -a
- sudo apt-get install mesa-common-dev libgl1-mesa-dev mesa-utils-extra libglapi-mesa ninja-build libqt4-dev qt4-qmake libqt4-opengl-dev

script:
  - cd bin
  - cmake -GNinja -DTRAVIS_BUILD:BOOL=${CMAKE_COMPILER_IS_GNUCC} ../Superbuild
  - travis_wait 80 ninja
  - cd SCIRun
  - ./Algorithm_Layer_Test
  - ./Modules_Factory_Tests --gtest_filter=*HardCodedModuleFactoryTests*

notifications:
  slack: sciinstitute:lZnpQQXNd4Io5iGDPQDpJmI1
