source:       .
destination:  ./_site

# Site title and subtitle. This is used in _includes/header.html
title: 'SCIRun 5'
subtitle: 'Modeling - Simulation - Visualization'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: ''

# Enable/show navigation. There are three options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 1

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/SCIInstitute/SCIRun'

# Default categories (in order) to appear in the navigation
sections: [
    ['start.html', 'Getting Started'],
    ['modules.html', "Modules"],
    ['user.html', 'User Documentation'],
    ['dev.html', 'Developer Documentation'],
    ['specs.html', 'Specifications'],
    ['support.html', 'Support'],
    ['faq.html', 'FAQ'],
    ['other.html', 'Other Links']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/scirun.pages'

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
kramdown:
  input:          GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
detach:       false
port:         9001
host:         127.0.0.1

description: Web pages for SCIRun
google_analytics:
show_downloads: true
theme: jekyll-theme-slate
