name: linux-build

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  linux-build-gui:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare
      run: sudo apt-get update && sudo apt-get install mesa-common-dev libgl1-mesa-dev mesa-utils-extra libglapi-mesa ninja-build qt5-qmake qtbase5-dev libqt5opengl5-dev libqt5svg5-dev

    - name: Build
      run: ./build.sh -DQt5_PATH=$(dpkg -L qtbase5-dev) -DUSER_PYTHON_VERSION="3.6.7" -j3

    - name: Basic Test
      working-directory: bin/SCIRun
      run: |
        cat ./SCIRun | head -c 1024

  linux-build-headless:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare
      run: sudo apt-get update && sudo apt-get install mesa-common-dev libgl1-mesa-dev mesa-utils-extra libglapi-mesa ninja-build

    - name: Build
      run: ./build.sh -DBUILD_HEADLESS:BOOL=ON -DUSER_PYTHON_VERSION="3.6.7" -DBUILD_TESTING:BOOL=ON -j3

    - name: Test
      working-directory: bin/SCIRun
      continue-on-error: true
      run: make test

  linux-build-gui-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare
      run: sudo apt-get update && sudo apt-get install mesa-common-dev libgl1-mesa-dev mesa-utils-extra libglapi-mesa ninja-build qt5-qmake qtbase5-dev libqt5opengl5-dev libqt5svg5-dev

    - name: Build
      run: ./build.sh -DQt5_PATH=$(dpkg -L qtbase5-dev) -DUSER_PYTHON_VERSION="3.6.7" -j3 -DBUILD_TESTING:BOOL=ON

    - name: Test
      working-directory: bin/SCIRun
      continue-on-error: true
      run: make test
