name: linux-build

on: [push, pull_request]

jobs:
  linux-build-gui:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Prepare
      run: sudo apt-get update && sudo apt-get install mesa-common-dev libgl1-mesa-dev mesa-utils-extra libglapi-mesa ninja-build qt5-qmake qtbase5-dev libqt5opengl5-dev libqt5svg5-dev

    - name: Build
      run: ./build.sh -DQT_MIN_VERSION="5.5" -DQt5_PATH=$(dpkg -L qtbase5-dev) -DUSER_PYTHON_VERSION="3.6.7" -DBUILD_TESTING:BOOL=ON -j3

    - name: Test
      working-directory: bin/SCIRun
      run: make test
