name: windows-build

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  windows-build-headless:
    runs-on: windows-2019

    steps:

    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure
      working-directory: bin
      shell: cmd
      run: |
        cmake ..\Superbuild -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" -Ax64 -DBUILD_HEADLESS:BOOL=ON -DBUILD_WITH_PYTHON:BOOL=OFF -DBUILD_TESTING:BOOL=ON

    - name: Compile
      working-directory: bin
      shell: cmd
      run: cmake --build . --config Release -j 3

    - name: Test
      working-directory: bin/SCIRun
      continue-on-error: true
      shell: cmd
      run: cmake --build . --target RUN_TESTS --config Release

  windows-build-gui-qt5:
    runs-on: windows-2019

    steps:

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        version: 5.15.2
        target: desktop
        host: windows
        arch: win64_msvc2019_64
        setup-python: 'true'
        install-deps: true

    - name: Print out Qt directory
      run: echo $Env:Qt5_Dir

    - name: Configure
      working-directory: bin
      run: |
        cmake ..\Superbuild -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" -Ax64 -DQt_PATH:PATH="$env:Qt5_Dir" -DBUILD_WITH_PYTHON:BOOL=OFF

    - name: Compile
      working-directory: bin
      shell: cmd
      run: cmake --build . --config Release -j 3

    - name: Package
      working-directory: bin/SCIRun
      shell: cmd
      continue-on-error: true
      run: cmake --build . --config Release --target package

    - name: Upload installer
      uses: actions/upload-artifact@v6
      continue-on-error: true
      with:
        name: SCIRunWindowsInstaller_qt5
        path: bin/SCIRun/SCIRun-5.0.*.exe

  windows-build-gui-qt6:
    runs-on: windows-2019

    steps:

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        version: 6.3.*
        target: desktop
        host: windows
        arch: win64_msvc2019_64
        setup-python: 'true'
        install-deps: true

    - name: Print out Qt directory
      run: echo $Env:Qt6_Dir

    - name: Configure
      working-directory: bin
      run: |
        cmake ..\Superbuild -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" -Ax64 -DSCIRUN_QT_MIN_VERSION:STRING="6.3.1" -DQt_PATH:PATH="$env:QT_ROOT_DIR" -DBUILD_WITH_PYTHON:BOOL=OFF

    - name: Compile
      working-directory: bin
      shell: cmd
      run: cmake --build . --config Release -j 3

    - name: Package
      working-directory: bin/SCIRun
      shell: cmd
      continue-on-error: true
      run: cmake --build . --config Release --target package

    - name: Upload installer
      uses: actions/upload-artifact@v6
      continue-on-error: true
      with:
        name: SCIRunWindowsInstaller_qt6
        path: bin/SCIRun/SCIRun-5.0.*.exe

  windows-build-gui-python:
    runs-on: windows-2019

    steps:

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        version: 5.15.2
        target: desktop
        host: windows
        arch: win64_msvc2019_64
        setup-python: 'true'
        install-deps: true

    - name: Configure
      working-directory: bin
      run: |
        cmake ..\Superbuild -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" -Ax64 -DQt_PATH:PATH="$env:Qt5_Dir"

    - name: Compile
      working-directory: bin
      shell: cmd
      run: cmake --build . --config Release -j 3

    - name: Package
      working-directory: bin/SCIRun
      shell: cmd
      continue-on-error: true
      run: cmake --build . --config Release --target package

    - name: Upload installer
      uses: actions/upload-artifact@v6
      continue-on-error: true
      with:
        name: SCIRunWindowsPythonInstaller
        path: bin/SCIRun/SCIRun-5.0.*.exe

    # - name: Deploy
    #   if: github.ref == 'refs/heads/master'
    #   uses: marvinpinto/action-automatic-releases@latest
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: "dev-windows"
    #     prerelease: true
    #     title: "Development Build for Windows"
    #     files: |
    #          bin/SCIRun/SCIRun-5.0.beta.*-win64.exe

  windows-build-gui-python-ospray:
    runs-on: windows-2019

    steps:

    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        version: 5.15.2
        target: desktop
        host: windows
        arch: win64_msvc2019_64
        setup-python: 'true'
        install-deps: true

    - name: Configure
      working-directory: bin
      run: |
        cmake ..\Superbuild -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" -Ax64 -DQt_PATH:PATH="$env:Qt5_Dir" -DWITH_OSPRAY:BOOL=ON

    - name: Compile
      working-directory: bin
      shell: cmd
      run: cmake --build . --config Release -j 3

    - name: Package
      working-directory: bin/SCIRun
      shell: cmd
      continue-on-error: true
      run: cmake --build . --config Release --target package

    - name: Upload installer
      uses: actions/upload-artifact@v6
      continue-on-error: true
      with:
        name: SCIRunWindowsOsprayInstaller
        path: bin/SCIRun/SCIRun-5.0.*.exe

    # - name: Deploy
    #   if: github.ref == 'refs/heads/master'
    #   uses: marvinpinto/action-automatic-releases@latest
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: "dev-windows"
    #     prerelease: true
    #     title: "Development Build for Windows"
    #     files: |
    #          bin/SCIRun/SCIRun-5.0.beta.*-win64.exe
  #
  # windows-better-build:
  #
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [windows-2022, windows-2019]
  #       qt: ["5.15.2", "6.3.1"]
  #       hl: ["ON", "OFF"]
  #       py: ["ON", "OFF"]
  #       osp: ["ON", "OFF"]
  #       tst: ["ON", "OFF"]
  #
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v6
  #
  #   - name: Print out config command
  #     run: echo "cmake ..\Superbuild -DCMAKE_BUILD_TYPE=Release -DWITH_OSPRAY:BOOL=${{ matrix.osp }} -DQt_PATH:STRING=${{ matrix.qt }}  -DBUILD_HEADLESS:BOOL=${{ matrix.hl }} -DBUILD_WITH_PYTHON:BOOL=${{ matrix.py }} -DBUILD_TESTING:BOOL=${{ matrix.tst }}"
