name: windows-build

on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  windows-build-headless:
    runs-on: windows-2019

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure
      working-directory: bin
      shell: cmd
      run: |
        cmake ..\Superbuild -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" -Ax64 -DBUILD_HEADLESS:BOOL=ON -DBUILD_WITH_PYTHON:BOOL=OFF -DBUILD_TESTING:BOOL=ON

    - name: Compile
      working-directory: bin
      shell: cmd
      run: cmake --build . --config Release -j 3

    - name: Test
      working-directory: bin/SCIRun
      continue-on-error: true
      shell: cmd
      run: cmake --build . --target RUN_TESTS --config Release

  windows-build-gui:
    runs-on: windows-2019

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        version: 5.15.2
        target: desktop
        host: windows
        arch: win64_msvc2019_64
        install-deps: true

    - name: Print out Qt directory
      run: echo $Env:Qt5_Dir

    - name: Configure
      working-directory: bin
      run: |
        cmake ..\Superbuild -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" -Ax64 -DQt_PATH:PATH="$env:Qt5_Dir" -DBUILD_WITH_PYTHON:BOOL=OFF

    - name: Compile
      working-directory: bin
      shell: cmd
      run: cmake --build . --config Release -j 3

    - name: Package
      working-directory: bin/SCIRun
      shell: cmd
      continue-on-error: true
      run: cmake --build . --config Release --target package

    - name: Upload installer
      uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: SCIRunWindowsInstaller
        path: bin/SCIRun/SCIRun-5.0.beta.*-win64.exe

  windows-build-gui-python:
    runs-on: windows-2019

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        version: 5.15.2
        target: desktop
        host: windows
        arch: win64_msvc2019_64
        install-deps: true

    - name: Configure
      working-directory: bin
      run: |
        cmake ..\Superbuild -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" -Ax64 -DQt_PATH:PATH="$env:Qt5_Dir"

    - name: Compile
      working-directory: bin
      shell: cmd
      run: cmake --build . --config Release -j 3

    - name: Package
      working-directory: bin/SCIRun
      shell: cmd
      continue-on-error: true
      run: cmake --build . --config Release --target package

    - name: Upload installer
      uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: SCIRunWindowsPythonInstaller
        path: bin/SCIRun/SCIRun-5.0.beta.*-win64.exe

    # - name: Deploy
    #   if: github.ref == 'refs/heads/master'
    #   uses: marvinpinto/action-automatic-releases@latest
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: "dev-windows"
    #     prerelease: true
    #     title: "Development Build for Windows"
    #     files: |
    #          bin/SCIRun/SCIRun-5.0.beta.*-win64.exe

  windows-build-gui-python-ospray:
    runs-on: windows-2019

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.14.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        version: 5.15.2
        target: desktop
        host: windows
        arch: win64_msvc2019_64
        install-deps: true

    - name: Configure
      working-directory: bin
      run: |
        cmake ..\Superbuild -DCMAKE_BUILD_TYPE=Release -G"Visual Studio 16 2019" -Ax64 -DQt_PATH:PATH="$env:Qt5_Dir" -DWITH_OSPRAY:BOOL=ON

    - name: Compile
      working-directory: bin
      shell: cmd
      run: cmake --build . --config Release -j 3

    - name: Package
      working-directory: bin/SCIRun
      shell: cmd
      continue-on-error: true
      run: cmake --build . --config Release --target package

    - name: Upload installer
      uses: actions/upload-artifact@v2
      continue-on-error: true
      with:
        name: SCIRunWindowsOsprayInstaller
        path: bin/SCIRun/SCIRun-5.0.beta.*-win64.exe

    # - name: Deploy
    #   if: github.ref == 'refs/heads/master'
    #   uses: marvinpinto/action-automatic-releases@latest
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: "dev-windows"
    #     prerelease: true
    #     title: "Development Build for Windows"
    #     files: |
    #          bin/SCIRun/SCIRun-5.0.beta.*-win64.exe
